version: 2

models:
  - name: stg_users
    columns:
      - name: user_id
        tests:
          - not_null
          - unique

      - name: email
        tests:
          - not_null

  - name: stg_plans
    columns:
      - name: plan_id
        tests:
          - not_null
          - unique

  - name: stg_subscriptions
    columns:
      - name: subscription_id
        tests:
          - not_null
          - unique

      - name: user_id
        tests:
          - not_null

      - name: plan_id
        tests:
          - not_null

  - name: stg_events
    columns:
      - name: user_id
        tests:
           - not_null

  - name: stg_payments
    columns:
      - name: user_id
        tests:
           - not_null
           
      - name: subscription_id
        tests:
           - not_null

