version: 2

sources:
  - name: raw
    database: SAAS_ANALYTICS
    schema: RAW
    tables:
      - name: users_raw
      - name: plans_raw
      - name: subscriptions_raw
      - name: events_raw
      - name: payments_raw
